[package]
name = "jup"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
base64 = "0.22.1"
bs58 = "0.5.1"
jup-ag-sdk = { path = "../jup-ag-sdk/" }
solana-client = "2.2.7"
solana-sdk = "2.2.2"
bincode = "1.3.3"
dotenv = "0.15.0"
